---
# File: tasks/Debian.yml - Debian/Ubuntu tasks for ansible-couchbase-server
# Download and install Couchbase Server

- name: Download
  get_url: url={{ couchbase_server_ubuntu_url }} dest=/tmp/{{ couchbase_server_ubuntu_package }} sha256sum={{ couchbase_server_ubuntu_sha256 }}
  tags: installation

- name: Install
  command: dpkg -i /tmp/{{ couchbase_server_ubuntu_package }}
  tags: installation
