---
# File: cluster_init.yml
# Example Ansible playbook to initialize a new Couchbase Server cluster

- hosts: cluster_nodes
  sudo: True
  tasks:
  - name: Create cluster grouping
    group_by: key={{ node_role }}

- hosts: cluster_nodes
  sudo: True
  roles:
    - brianshumate.couchbase-server
  tasks:
  - name: Couchbase Server Service
    service: name=couchbase-server state=started

- hosts: primary
  sudo: True
  vars_files:
    - roles/brianshumate.couchbase-server/defaults/main.yml 
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['inventory_hostname']}}"
  tasks:
   
  - name: Initialize primary node
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli cluster-init -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --cluster-init-username={{ couchbase_server_admin }} --cluster-init-password={{ couchbase_server_password }} --cluster-init-port={{couchbase_server_admin_port}} --cluster-init-ramsize={{ couchbase_server_ram }}"
        
  - name: Join additional cluster nodes
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli server-add -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add={{hostvars[[item][0]]['inventory_hostname']}}:{{ couchbase_server_admin_port }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }}"       
    with_items: groups['additional']

  - name: Rebalance cluster
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli rebalance -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --server-add-username={{ couchbase_server_admin }} --server-add-password={{ couchbase_server_password }}"
