---
# File: create_bucket.yml
# Example Ansible playbook to create a new Couchbase Server bucket

- hosts: cluster_nodes
  sudo: True
  tasks:
  - name: Create cluster grouping
    group_by: key={{ node_role }}

- hosts: primary
  sudo: True
  gather_facts: False
  vars_files:
    - roles/couchbase.couchbase-server/defaults/main.yml
  #roles:
  #  - brianshumate.couchbase-server
  vars:
    couchbase_server_primary_node: "{{hostvars[groups['primary'][0]]['inventory_hostname']}}"
    couchbase_server_bucket_name: makura
    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_ram: 256
    couchbase_server_bucket_port: 11222
    couchbase_server_bucket_replica: 1

# FIXME: need to find a way to make this work with `-e` vars too
#  vars_prompt:
#    - name: "b_name"
#      prompt: "Bucket name"
#      default: "makura"
#      private: no
#    - name: "b_type"
#      prompt: "Bucket type"
#      default: "couchbase"
#      private: no
#    - name: "b_ramsize"
#      prompt: "Bucket RAM Size (MB)"
#      default: "256"
#      private: no
#    - name: "b_port"
#      prompt: "Bucket port"
#      default: "11222"
#      private: no
#    - name: "b_replica"
#      prompt: "Bucket replica (1-3)"
#      default: "1"
#      private: no

  tasks:
    - name: Create new bucket
      shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-create -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }} --bucket={{ couchbase_server_bucket_name }} --bucket-type={{ couchbase_server_bucket_type }} --bucket-port={{ couchbase_server_bucket_port }} --bucket-ramsize={{ couchbase_server_bucket_ram }} --bucket-replica={{ couchbase_server_bucket_replica }}"
